In [122]:
import numpy as np

In [123]:
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [124]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [125]:
%timeit [j**4 for j in range(1,9)]

3.83 μs ± 761 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [126]:
import numpy as np
%timeit np.arange(1,9)**4

The slowest run took 99.66 times longer than the fastest. This could mean that an intermediate result is being cached.
84.5 μs ± 150 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [127]:
#  Arrays

In [128]:
# To create Numpy array use np.array()
a=np.array([1,2,3])
print(a)

[1 2 3]


In [129]:
# 2 dimension
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [130]:
# to check for dimension
a.ndim

2

In [131]:
# itemsize
a.itemsize
a.dtype

dtype('int64')

In [132]:
a.size # it will count total elements in list
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [133]:
a.shape
# here it gives (3,2)
# it means 3 rows and 2 columns

(3, 2)

In [134]:
b=np.array([[1,2],[3,4],[5,6]],dtype=complex)
print(b)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [135]:
x=np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [136]:
y=np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [137]:
np.arange(1,5)

array([1, 2, 3, 4])

In [138]:
# step function
np.arange(1,5,2)
# so it will start as 1 and then take the step of 2 so it will take 3

array([1, 3])

In [139]:
# 3 dimension array
t=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(t)
print(t.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [140]:
# create an array using Numpy function

In [141]:
# Empty arrays

In [142]:
ar=np.empty(4)
print(ar)

[0.0e+000 2.5e-323 2.5e-323 2.5e-323]


In [143]:
# array diagonal element filled with 1's

In [144]:
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [145]:
x=np.eye(3,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [146]:
# create an array with values that are spaced linearly in a specified interval

In [147]:
# np.linspace(start,stop,num='')
x=np.linspace(1,10,7)
print(x)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [148]:
y=np.linspace(1,10,20)
print(y)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [149]:
# reshape the array
x=np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.shape)
print(x.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 3]
 [4 5 6]]


In [150]:
# mathematical operation

In [151]:
x.min()
x.max()
x.sum()


np.int64(21)

In [152]:
# now here axis=0 means column wise and axis=1 means row
x.sum(axis=0)

array([ 9, 12])

In [153]:
x.sum(axis=1)

array([ 3,  7, 11])

In [154]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [155]:
np.std(a)

np.float64(1.707825127659933)

In [156]:
# operations
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [157]:
# matrix products
print(a.dot(b))

[[19 22]
 [43 50]]


In [158]:
# INDEXING AND SLICING

In [159]:
# 1. List
n=[1,2,3]
print(n[0:2])
print(n[-1])

[1, 2]
3


In [160]:
# 2. array
a=np.array([1,2,3])
print(a[0:2])
print(a[-1])

[1 2]
3


In [161]:
# both array and list works same
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(x[1,2]) 
# row=1 and column=2 
# every row and column start with 0
print(x[0:2,2])
print(x[-1])
print(x[-1,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[3 6]
[7 8 9]
[7 8]


In [162]:
# ITERATE THROUGH ARRAY
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a
for row in a:
    print(row)
# to get every element separately
for cell in a.flat:
    print(cell)


[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


In [163]:
# sticking two array
a=np.arange(0,6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
# for vertical join use vstack
np.vstack((a,b))
# for horizontal join use hstack
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [164]:
a=np.arange(30).reshape(2,15)
a
np.hsplit(a,3)
np.vsplit(a,2)


[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [165]:
# Indexing with boolean array
a=np.arange(12).reshape(3,4)
b=a>4
b
# Indexing `a` with boolean array `b`:
# `a[b]` returns a flattened array of `a` containing only the elements where `b` is True.
a[b]

a[b]=-1
a



array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [166]:
# We uses np.nditer to iterate over a NumPy array in different memory orders.
a=np.arange(12).reshape(3,4)
a
for x in np.nditer(a,order='C'):
    print(x)
for x in np.nditer(a,order='F'):
    print(x)

"""
 In C-order, elements are iterated over in a row-major order, meaning that it iterates over the array row by row.
 In F-order, elements are iterated over in a column-major order, meaning that it iterates over the array column by column.

Original Array a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Iteration in C-order:
0 1 2 3 4 5 6 7 8 9 10 11

Iteration in F-order:
0 4 8 1 5 9 2 6 10 3 7 11

"""


0
1
2
3
4
5
6
7
8
9
10
11
0
4
8
1
5
9
2
6
10
3
7
11


'\n In C-order, elements are iterated over in a row-major order, meaning that it iterates over the array row by row.\n In F-order, elements are iterated over in a column-major order, meaning that it iterates over the array column by column.\n\nOriginal Array a:\n[[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]\n\nIteration in C-order:\n0 1 2 3 4 5 6 7 8 9 10 11\n\nIteration in F-order:\n0 4 8 1 5 9 2 6 10 3 7 11\n\n'

In [167]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)
# order='F': Specifies iteration in column-major (Fortran) order.
# flags=['external_loop']: Aggregates elements into larger chunks (usually rows or columns) rather than iterating element by element.


[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [168]:
a=np.arange(3,15,4).reshape(3,1)
a
'''
np.arange(start, stop, step) creates an array with values starting from start (inclusive), up to stop (exclusive), with increments of step.

In this case, start=3, stop=15, and step=4.

This generates the following array:

python
Copy code
[3, 7, 11]
Explanation:

Starts at 3
Adds 4 to get the next value (3 + 4 = 7)
Adds 4 again to get the next value (7 + 4 = 11)
Stops before reaching 15, so the array ends at 11.
'''


'\nnp.arange(start, stop, step) creates an array with values starting from start (inclusive), up to stop (exclusive), with increments of step.\n\nIn this case, start=3, stop=15, and step=4.\n\nThis generates the following array:\n\npython\nCopy code\n[3, 7, 11]\nExplanation:\n\nStarts at 3\nAdds 4 to get the next value (3 + 4 = 7)\nAdds 4 again to get the next value (7 + 4 = 11)\nStops before reaching 15, so the array ends at 11.\n'

In [169]:
# BROADCAST RULE
'''
Arrays are compatible when:
The dimensions are equal, or
One of the dimensions is 1.**
'''
x=np.array([[1],[2]])
x.shape
y=np.arange(6).reshape(2,3)
y
print(x*y)

[[ 0  1  2]
 [ 6  8 10]]


In [170]:
"""
Detailed Explanation
Original Shapes:

x has shape (2, 1)
y has shape (2, 3)
Broadcasting Process:

Align Dimensions: Start from the rightmost dimensions and compare.
For x with shape (2, 1), the dimensions are (2, 1).
For y with shape (2, 3), the dimensions are (2, 3).
Comparing Dimensions:
Rightmost dimension: 1 from x and 3 from y.
Broadcasting Rule: If one of the dimensions is 1, it can be broadcast to the larger dimension. Hence, x's dimension 1 will be broadcast to match y's dimension 3.
Next dimension: 2 (from both x and y).
These dimensions are already compatible as they are the same.
Broadcasting Expansion:


[[1, 1, 1],
 [2, 2, 2]]
This expanded array has shape (2, 3) which matches y.
"""

"\nDetailed Explanation\nOriginal Shapes:\n\nx has shape (2, 1)\ny has shape (2, 3)\nBroadcasting Process:\n\nAlign Dimensions: Start from the rightmost dimensions and compare.\nFor x with shape (2, 1), the dimensions are (2, 1).\nFor y with shape (2, 3), the dimensions are (2, 3).\nComparing Dimensions:\nRightmost dimension: 1 from x and 3 from y.\nBroadcasting Rule: If one of the dimensions is 1, it can be broadcast to the larger dimension. Hence, x's dimension 1 will be broadcast to match y's dimension 3.\nNext dimension: 2 (from both x and y).\nThese dimensions are already compatible as they are the same.\nBroadcasting Expansion:\n\n\n[[1, 1, 1],\n [2, 2, 2]]\nThis expanded array has shape (2, 3) which matches y.\n"