In [3]:
# NUMPY ARRAY SLICING
# Slicing in python means taking element from one givenindex to another index
# we pass slice instead of index like this:[start:end]
# We can also define the step like this [start:end:step]

In [5]:
import numpy as np


In [9]:
a1=np.array([1,2,3,4,5,6,7])
a1[1:5] #[start:end]
a1[4:]
a1[:4]

array([1, 2, 3, 4])

In [17]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]]) # slicing 2d array
print(a2)
a2[1,1:4] #[row:col]
a2[0:2,2]
"""
a2[1, 1:4]:
Row: 1 (second row)
Columns: 1:4 (columns from index 1 to index 3)

a2[0:2, 2]:
Rows: 0:2 (first and second rows)
Column: 2 (third column)
"""

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


'\na2[1, 1:4]:\nRow: 1 (second row)\nColumns: 1:4 (columns from index 1 to index 3)\n\na2[0:2, 2]:\nRows: 0:2 (first and second rows)\nColumn: 2 (third column)\n'

In [20]:
print(a2[0:2,1:4])
"""
a2[0:2, 1:4]:
Rows: 0:2 (first and second rows)
Column: 1:4 (column 1 to column 3)
"""


[[2 3 4]
 [7 8 9]]


'\na2[0:2, 1:4]:\nRows: 0:2 (first and second rows)\nColumn: 1:4 (column 1 to column 3)\n'

In [30]:
a3 =np.array([[[10,11,12],[13,14,15]],  # slicing 3d array
              [[20,21,22],[23,24,25]],
              [[26,27,28],[29,30,31]]])
a3


array([[[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]],

       [[26, 27, 28],
        [29, 30, 31]]])

In [34]:
#This array has a shape of (3, 2, 3):

#Depth (first dimension): 3
#Rows (second dimension): 2
#Columns (third dimension): 3

In [ ]:
"""
 Breaking Down the Slicing a3[:2, 1:, :2]
Let's break down the slicing step by step:

a3[:2, ...]:

:2 selects slices from the start up to (but not including) index 2 along the first dimension (depth).
This means you select the first 2 depth layers of the array. In this case, you get the first two 2D arrays:
python
Copy code
[[[10, 11, 12],
  [13, 14, 15]],
 
 [[20, 21, 22],
  [23, 24, 25]]]
a3[:2, 1:, ...]:

1: selects rows starting from index 1 to the end along the second dimension (rows).
This means you select only the rows from index 1 in each of the 2D slices (the second row). The result is:
python
Copy code
[[13, 14, 15],
 [23, 24, 25]]
a3[:2, 1:, :2]:

:2 selects columns from index 0 to 1 along the third dimension (columns).
This means you select only the first two columns. The result is:
python
Copy code
[[13, 14],
 [23, 24]]
Putting It All Together
Combining all the slices, a3[:2, 1:, :2] selects:

Depth layers: The first 2 depth layers of a3.
Rows: The rows starting from index 1 to the end.
Columns: The columns from index 0 to 1.
"""

In [35]:
# VIEW VS COPY

# copy is a new array, and the view is just a view of original array.
# Any changes made to the copy will not affect original array
# any changes made to the view will affect the original array 

In [41]:
arr=np.array([1,2,3,4,5])
# copy method
copy=arr.copy()
copy[0]=45
print(arr)
print(copy)

[1 2 3 4 5]
[45  2  3  4  5]


In [45]:
# VIEW METHOD
view=arr.view()
view[0]=89
print(arr)


[89  2  3  4  5]
[89  2  3  4  5]
