In [2]:
# NUMPY RESHAPING INDEX
 # Reshaping means changing the shape of an array

In [1]:
import numpy as np


In [6]:
arr=np.arange(12) # 1D ARRAY
# 1D TO 2D ARRAY
new=arr.reshape(4,3)
print(new)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# 1D to 3D
x=arr.reshape(2,3,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [9]:
# ARRAY INDEXING

# Array indexing is the same as accessing an array element
# You can acess any  array element by referring to its index number

In [13]:
arr=np.array([1,2,3,4]) # Acessing 1d array
print(arr[1])
print(arr[2]+arr[3])

2
7


In [23]:
arr=np.array([[1,2,3,7,8],[4,5,6,9,10]]) # Acessing 2D array
print(arr)
print(arr[0,2]) # 1 st row and 3nd element because here it starts with 0
print(arr[1,4]) # 2 nd row 5TH element

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]
3
10


In [34]:
arr=np.array([[[1,2,3,45,5],[6,7,8,9,10],[11,12,13,14,15]]]) # Acessing 3D array
print(arr)
print(arr[0,2,4])
# When you want to access elements in this 3D array, you use three indices: [depth, row, column].
#arr[0] selects the only 2D array.
#arr[0, 1] selects the second row of that 2D array.
#arr[0, 1, 2] selects the third column of that row.

[[[ 1  2  3 45  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
15


In [43]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,1,2]) # 1 st matrix 1 st row 2 nd column


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12
