In [1]:
# APPEND,INSERT AND DELETE OPERATION

In [2]:
import numpy as np

In [10]:
a=np.array([[1,2,3],[4,5,6]])
# append method
np.append(a,[7,8,9])
np.append(a,[[7,8,9]],axis=0) # axis=0 means row
np.append(a,[[5],[8]],axis=1) # axis=1 means col

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [24]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
# insert method
np.insert(a,3,[11,12])
np.insert(a,1,[13,14],axis=0)
np.insert(a,2,[[15,16,17]],axis=1)

[[1 2]
 [3 4]
 [5 6]]


array([[ 1,  2, 15],
       [ 3,  4, 16],
       [ 5,  6, 17]])

In [31]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
# delete method
np.delete(a,5) # delete 5 th index element
np.delete(a,1,axis=0)
np.delete(a,2,axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
# NUMPY CONCATENATION

# It is used to joined two or more array of same shape along a specified axis
# Axis=0 Adding new row
# Axis=1 Adding new column


In [42]:
arr1=np.array([[2,4],[5,6]])
print(arr1)
arr2=np.array([[7,8],[9,10]])
print(arr2)
new=np.concatenate((arr1,arr2),axis=0)
print(new)
new=np.concatenate((arr1,arr2),axis=1)
print(new)


[[2 4]
 [5 6]]
[[ 7  8]
 [ 9 10]]
[[ 2  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 2  4  7  8]
 [ 5  6  9 10]]
